[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "python"
auto-format = true
language-servers = ["basedpyright", "ruff"]

[[language]]
name = "dockerfile"
file-types = [
  "Dockerfile",
  { glob = "Dockerfile" },
  { glob = "Dockerfile.*" },
  { glob = "Dockerfile-*" },
  "dockerfile",
  { glob = "dockerfile" },
  { glob = "dockerfile.*" },
  "Containerfile",
  { glob = "Containerfile" },
  { glob = "Containerfile.*" },
  "containerfile",
  { glob = "containerfile" },
  { glob = "containerfile.*" },
]
